-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Asmlang.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Asmlang.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Asmlang.Abs.Ident -> Result
transIdent x = case x of
  Asmlang.Abs.Ident string -> failure x

transPgm :: Asmlang.Abs.Pgm -> Result
transPgm x = case x of
  Asmlang.Abs.PDefs primitives -> failure x

transPrimitive :: Asmlang.Abs.Primitive -> Result
transPrimitive x = case x of
  Asmlang.Abs.PInst instruction -> failure x
  Asmlang.Abs.PLabel label -> failure x

transLabel :: Asmlang.Abs.Label -> Result
transLabel x = case x of
  Asmlang.Abs.Llabel ident -> failure x

transInstruction :: Asmlang.Abs.Instruction -> Result
transInstruction x = case x of
  Asmlang.Abs.Inop -> failure x
  Asmlang.Abs.Iipush integer -> failure x
  Asmlang.Abs.Iiadd -> failure x
  Asmlang.Abs.Iiprint -> failure x
  Asmlang.Abs.Ibranch label -> failure x
  Asmlang.Abs.Idup -> failure x
  Asmlang.Abs.Ibeq label -> failure x
  Asmlang.Abs.Ibne label -> failure x
  Asmlang.Abs.Iiload address -> failure x
  Asmlang.Abs.Iistore address -> failure x
  Asmlang.Abs.Iexit -> failure x

transAddress :: Asmlang.Abs.Address -> Result
transAddress x = case x of
  Asmlang.Abs.Aaddress integer -> failure x
