-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language asmlang.

module Asmlang.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Pgm = PDefs [Primitive]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Primitive = PInst Instruction | PLabel Label
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Label = Llabel Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Instruction
    = Inop
    | Iipush Integer
    | Iiadd
    | Iiprint
    | Ibranch
    | Idup
    | Ibeq Label
    | Ibne Label
    | Iexit
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

